// Generated by Wrangler on Mon Sep 02 2024 01:47:13 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	DATABASE_URL: string;
	SUPABASE_URL: string;
	SUPABASE_KEY: string;
	SUPABASE_JWT_SECRET: string;
	SUPABASE_ANON_KEY: string;
	SUPABASE_DB_PASSWORD: string;
}
