// Generated by Wrangler on Tue Sep 03 2024 06:18:26 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
  DATABASE_URL: string
  SUPABASE_URL: string
  SUPABASE_KEY: string
  SUPABASE_JWT_SECRET: string
  SUPABASE_ANON_KEY: string
  SUPABASE_DB_PASSWORD: string
  SESSION_SECRET: string
  NODE_ENV: string
}
